coffee_rewarder:
  cron: "0 0 1 * *"
  class: "CoffeeRewarderJob"
new_year_points_expirer:
  cron: "0 0 1 1 *"
  class: "PointsExpiryJob"
movie_ticket_rewarder:
  cron: "0 1 * * *"
  class: "MovieTicketRewarderJob"
cash_rebate_awarder:
  cron: "0 3 1 * *"
  class: "CashRebateJob"
birthday_rewarder:
  cron: "0 2 1 * *"
  class: "BirthdayMonthRewardJob"
